### ISSUE TITLE
Combine Vikfield's graphical changes as an option

### ISSUE THREAD

**Issue by maxim-zhao** [maxim-zhao/psrp#104]
If we have space... make the "CSI" and "Makeover" changes an option?

**Comment by maxim-zhao** [comment]
https://www.romhacking.net/hacks/5248/

https://www.romhacking.net/hacks/6273/

This is straying from the "original game" so it should definitely be opt-in. Some changes will be harder to implement than others...

**Comment by maxim-zhao** [comment]
Also: I'm open to feedback from others on whether this is a good idea.

**Comment by gensakudan** [comment]
Definitely a hard no from me. I feel like this goes *way* beyond the scope of a retranslation.

**Comment by eltonbor** [comment]
I agree with @gensakudan, this is moving away too much from the original game.

**Comment by maxim-zhao** [comment]
A forked version of the retranslation would be possible, the framework is all there for script mods and art hacks. But it'd be some work to maintain.
