### ISSUE TITLE
Saturn/PS2 hiragana ROM support

### ISSUE THREAD

**Issue by DrAzathoth** [maxim-zhao/psrp#107]
Would it be possible to add support for the alternate Japanese hiragana ROM from the two Phantasy Star collections?

**Comment by gensakudan** [comment]
As I recall, those versions are either glorified ports, or ROM hacks running in what's essentially an emulator for a souped-up Master System with multiple VRAM pages. For original hardware, we're lacking the VRAM space to literally double the character count, and while doing something like dynamically loading in only the characters that are currently needed would be possible *in theory*, I'm pretty sure there are too many unknowns for implementation to be in any way feasible.

**Comment by maxim-zhao** [comment]
I don't think there's anything to gain from this versus patching the original Japanese ROM. Making a ROM hack support multiple base ROMs would be a great deal of work.
