### ISSUE TITLE
No 2.4.1 files are available

### ISSUE THREAD

**Issue by Raton-Laveur** [maxim-zhao/psrp#115]
The releases only [include up to 2.3.1](https://github.com/maxim-zhao/psrp/releases), and [SMS Power hosts up to 2.4](https://www.smspower.org/Translations/PhantasyStar-SMS-EN).

2.4.1 is not on this repo, and [only found on the French version page of SMS Power](https://www.smspower.org/Translations/PhantasyStar-SMS-FR). 

I know the difference from 2.4 to 2.4.1 is only related to the french version, but 

1. the french version is not available on this repo even though it's listed in the readme,
2. the releases are still up to 2.3.1.

**Comment by maxim-zhao** [comment]
Now fixed.
