### ISSUE TITLE
Typo in battle dialogue

### ISSUE THREAD

**Issue by SavagePencil** [maxim-zhao/psrp#21]
> [210d]
> ;<monster>ハ ニゲアシノ<line>
> ;ハヤサニ オドロイタ.<delay>
> <Article><monster> was surprised by the speed of the your escape.<delay>

`"by the speed of the your escape"` should be

`"by the speed of your escape"`

**Comment by maxim-zhao** [comment]
Good catch - and easy to fix if you fancy having a go.
