### ISSUE TITLE
Experience can no longer be earned

### ISSUE THREAD

**Issue by frankcifaldi** [maxim-zhao/psrp#23]
Tested on latest, suspect it's due to added experience multiplier. After winning a battle, the expected "You have earned [x] experience" text never prints, and no experience is earned.

Tested on a new game with no options set, and on a continued game with both 2x and 3x experience multiplier set.

![noexp_01](https://user-images.githubusercontent.com/46167690/69510537-3c042300-0ef2-11ea-9cef-3bfd5c5b85bb.png)
![noexp_02](https://user-images.githubusercontent.com/46167690/69510538-3f97aa00-0ef2-11ea-9da1-683414e8dbc5.png)

**Comment by maxim-zhao** [comment]
Some correlation perhaps to committing at 1:30am.

**Comment by maxim-zhao** [comment]
Did you use a save state? The code is applying a multiplier from a location that's defaulted to 0... I might change the code to treat that as a x1 instead.
