### ISSUE TITLE
Allow button 1 to act as "Return" on title screen sub-menus

### ISSUE THREAD

**Issue by frankcifaldi** [maxim-zhao/psrp#24]
Button 1 acts as "cancel" in the game for pop-up menus, i.e. in the shop. Players may expect this functionality on the new title screen pop-up menus (soundtrack, load game options, game enhancement options).

**Comment by maxim-zhao** [comment]
Can do. The original is a bit inconsistent in the continue menu and I took the easy route, but it’s just a few extra instructions to check this.
