### ISSUE TITLE
Can't exit from "Load Game" if no saved games are present

### ISSUE THREAD

**Issue by frankcifaldi** [maxim-zhao/psrp#25]
Steps:

1. Start a new game with no existing saves
2. Create a saved game in slot 1
3. Reset the console
4. Select Continue on title screen
5. Select delete game
6. Delete the saved game in slot 1
7. Select continue
8. Observe: Empty save list appears. Player is unable to do anything but reset

**Comment by maxim-zhao** [comment]
It's supposed to do what the original did - start a new game instead.
