### ISSUE TITLE
Man in Casba says dialogue from Aerocastle

### ISSUE THREAD

**Issue by frankcifaldi** [maxim-zhao/psrp#28]
Old man in the peaceful town of Casba says threatening-ass line from the end of the game, specifically 51a6 in script.txt.

I'm guessing this line is shared, and I should write a non-threatening version? I don't remember this line from the first time we worked on this...

Kega Fusion save state attached

![wrongdialogue_01](https://user-images.githubusercontent.com/46167690/69837441-afb07380-1203-11ea-9ad1-37f5d8e514ef.png)
![wrongdialogue_02](https://user-images.githubusercontent.com/46167690/69837442-b212cd80-1203-11ea-93ed-547deff39b06.png)

[ps1jert.sso.zip](https://github.com/maxim-zhao/psrp/files/3903346/ps1jert.sso.zip)

**Comment by maxim-zhao** [comment]
SRAM save please?

**Comment by frankcifaldi** [comment]
Sorry, I sent the wrong file, SSX attached here
[casba_angry_man.zip](https://github.com/maxim-zhao/psrp/files/3905713/casba_angry_man.zip)

**Comment by maxim-zhao** [comment]
As a technical note, the hex addresses in the script now refer to exactly where in the ROM the line is used, and as such when there's more than one place using it there's usually more than one address.

Next thing to note is that both of your attachments are not SRAM saves (the 8KB on-cart save). It seems Kega doesn't spit this out as a separate file - which is sort of reasonable, but means you can't move saves between emulators except by careful hex editing.

As for this one - indeed it seems the game does use the same script in both places. I'll confirm with the Japanese version before closing.

**Comment by maxim-zhao** [comment]
Casba:
![image](https://user-images.githubusercontent.com/7792986/70269284-fd942100-1799-11ea-8c32-300bd78b4cb2.png)
Aerocastle:
![image](https://user-images.githubusercontent.com/7792986/70269317-0b49a680-179a-11ea-80c7-bad8948a2fbd.png)
I could make them say different things... but it's a bit of a pain.
