### ISSUE TITLE
Credits text does not display correctly

### ISSUE THREAD

**Issue by frankcifaldi** [maxim-zhao/psrp#29]
See image. The credits display correctly in the first (blue-palette) dungeon, but break when the sequences falls into the second (green palette) dungeon and never recovers.
![image](https://user-images.githubusercontent.com/46167690/69908993-8e3cbc80-13a8-11ea-84f2-4bd8ee153bbf.png)

**Comment by maxim-zhao** [comment]
Ah... the is a side effect of the way the game loads fonts after dungeon pitfalls. Good catch :)
