### ISSUE TITLE
Stuck in a loop when trying to sell when you have no items

### ISSUE THREAD

**Issue by maxim-zhao** [maxim-zhao/psrp#35]
Presumably a bug in the original? Start a new game, go to the tool shop, choose "Sell", and you're stuck there forever.

**Comment by MandrasX** [comment]
No, this is actually an error caused by something you did with the redone menu system. You can back out of this screen in v1.02 and vanilla.

**Comment by maxim-zhao** [comment]
The original code was relying on bit 4 of `c` being set as a side effect of drawing the inventory screen. The fix is to set it explicitly.
