### ISSUE TITLE
Script junk

### ISSUE THREAD

**Issue by maxim-zhao** [maxim-zhao/psrp#36]
https://www.smspower.org/forums/post108879#108879
https://www.smspower.org/forums/post108913#108913

Two garbage script pointers, need to figure out where?

**Comment by MandrasX** [comment]
[52c4]
; Dishonest Dezorian
; [1E6]
; コノブラクハ パルマノ ヒトビトヲ<line>
; カンゲイシマス.<wait>
; This village welcomes Palmans.
This village welcomes all Palmans. Seriously!<wait>

///Should be a pointer here? In v1.02 it says "Those guys in the other village are all liars. 
///For real." In the beta is it messed up.
[DishonestDezorianFix]
; Dishonest Dezorian
; コノムラハ ソピァト イイマス.
; The neighboring villagers are all liars. Be careful.
; [1E7]
The neighboring villagers lie. Really!<wait>

**Comment by MandrasX** [comment]
The other one is the old man at the top right in "Palma - Passageway To Abion Island" 
https://www.smspower.org/Maps/PhantasyStar-SMS?gallerypage=Palma+-+Passageway+To+Abion+Island

**Comment by maxim-zhao** [comment]
Thanks!

**Comment by maxim-zhao** [comment]
> The drug store in Avion Village sells Polymeteral
This one was fixed by be8660d1b05193b265c958fd659596b4cf7ee5c1
