### ISSUE TITLE
sound toggle to FX chip not working when running in Mac OS OpenEmu

### ISSUE THREAD

**Issue by JA-games** [maxim-zhao/psrp#51]
I was a bit bummed to discover I could not play your patch with FX Sound enabled. With that said, on the main menu under Sound, the Chip is stuck on SN76489. I assume I hit a button or toggle left or right to switch to the FM chip audio.. well, no such luck.

Running on MacOS, OpenEmu.

One suggestion, since the FM sound is soooooo much better, maybe make that the default, and then if one so chooses, can access the Sound menu and toggle it to the regular *far less cool* SMS version.

**Comment by maxim-zhao** [comment]
FM is not available if not detected by the game. Your emulator is not emulating it :)
