### ISSUE TITLE
pt-BR translation

### ISSUE THREAD

**Issue by maxim-zhao** [maxim-zhao/psrp#52]
Let's use GitHub issues to track some work! This one can track the things that need doing and we can raise more issues for anything that's worth it.

- [x] Script for pt-BR, from script by @ajkmetiuk
  - [x] Script changes based on the 2.0 English text changes
- [x] Items, menus
  - [x] Menu resizing (as needed)
  - [x] Window cache rearrangement
- [x] Font mapping based on what's used in the script
  - [x] Font reworking for both fonts based on this
  - [x] Relocating scripting codes to make room for a longer alphabet
  - [x] Bug introduced by the above causes a glitch tile after every article...
- [x] Article handlers
  - [x] Some "named" enemies like LaShiec need to have possessive (do) but no article when they are named, this is an extra variant to add (similar to French)
- [x] Optimisation of dictionary size (as needed)
  - [x] Should re-do it after script updates
- [x] Name entry screen
- [x] Credits
  - [x] complete translation
- [x] Title screen
  - [x] Extra info if there is space
- [x] SHOP and EXIT signs

**Comment by maxim-zhao** [comment]
This font is designed to support additional accented characters by increasing the amount of tile-flipping that can be done, sometimes at the cost of uglier letters.
![image](https://user-images.githubusercontent.com/7792986/104495284-7c7ba000-55cf-11eb-8ca3-064936d27bdb.png)
Credit to Master Emerald in the SMS Power! Discord channel. However this may need some work based on the characters we need, and it's also a loss of both the fonts in 2.0 English. Hopefully we can adapt them to this model.

**Comment by ajkmetiuk** [comment]
hmm, sounds cool, taking base in french accented font (by 2.02)...

K=ã
W=í
X=ó
Y=â
à
é
ê
è=á
g=ú
’=ç
u=õ
w=ô


W=(M vflip)
q=(p hflip)
w=(m vflip)
u=(n vflip)
d=(b hflip)
g=(6 vflip)
0=O
l=1
'="

**Comment by maxim-zhao** [comment]
The English font uses 5px for the lowercase parts ("x-height"), with 2px above and 1px below. This means that v-flips don't align properly: here's a quick demo:

![image](https://user-images.githubusercontent.com/7792986/104659671-f3429700-56bc-11eb-9e81-de3ba3424163.png)

This is the "AW2284" font which is based on Phantasy Star IV. The "Polaris" font is more tricky to edit - it was made by [a talented pixel font guy](https://damieng.com/typography/zx-origins/). Editing either of them to 4px x-height will be tricky.

**Comment by maxim-zhao** [comment]
Anyway, I've inserted the script and menus. There's some work needed to accommodate the wider menus in some places, so they will draw corrupted for now. I added `TODO-pt-br` to a couple of places in the asm where some translation is needed.

In the items list, I need to understand the articles needed. For French, we had to cover a matrix of:

|                   | Vowel | Masculine | Feminine | Plural | Name with vowel | Name with consonant |
|-------------------|-------|-----------|----------|--------|-----------------|---------------------|
| Lower `<article>` | l'    | le        | la       | les    |                 |                     |
| Upper `<Article>` | L'    | Le        | La       | Les    |                 |                     |
| Possessive `<de>` | de l' | du        | de la    | des    | d'              | de                  |
| Directive `<à>`   | à     | au        | à la     | aux    | à               | à                   |

The pt-br script currently has no cases for articles. `<use article 02>` seems to be directive, and there's no possessive equivalent - is that right?

**Comment by maxim-zhao** [comment]
The script could use a proof-read. There's missing capitalisation on names, and I'm not sure what the pt-br convention is on capitalising item names in text - for example, the English text would say "Do you have a Roadpass?", should pt-br be "Você tem um passe?" or "Você tem um Passe?"? Elsewhere it will use the capitalised name when inserting in place of an `<item>` code, so maybe better to be capitalised? 

I may also have missed some hyphens in the conversion - they will come out as "u". Please fix them!

**Comment by maxim-zhao** [comment]
The accented character list (from the script, I didn't count the menus or names) is:

ã x 243
á x 236
à x 11
â x 5
Á x 1
ç x 90
ê x 344
é x 544
É x 16
í x 34
ó x 53
õ x 8
ô x 12
Ó x 1
ú x 19

That's 15, which is possible with the "???" font above but that has some ugly tile hacks, and requires the font editing I mentioned above. Obviously with uppercase-only, there's plenty of tile space. If you can avoid the uppercase Á and Ó then it makes it a bit easier - they are used for "Árvores Laerma possuem frutas estranhas" and "Ótimo".

**Comment by ajkmetiuk** [comment]
> how do these map?

actually there are 6, o, a, do, da, um, uma, I set up a table to explain it better, um/uma is used in items. Example: "usou uma PelorieMate", "Equipou um Escudo de Couro". do/da is used in battle. Example: "desviou do ataque da Medusa", "desviou do ataque do Escorpião". The Upper in the script will only use "O" and "A", Example: "O Escorpião desviou do ataque" "A Lente Dourada desviou do ataque" The plurals only the "as" will be used in "as Frutas de Laerma". the rest it seems that there will be no need...
![13](https://user-images.githubusercontent.com/46766099/104756808-08f6a180-573b-11eb-8167-d256f3eeee73.jpg)

**Comment by ajkmetiuk** [comment]
> so maybe better to be capitalised?

It's same as English. This is correct, "Você tem um Passe?". Is capitalised because of item reference.

**Comment by ajkmetiuk** [comment]
> If you can avoid the uppercase Á and Ó then it makes it a bit easier.

there is a way to replace, I will check this too and I will try to remove all É if possible I can put something else at the beginning of the sentence to remove this capitalized É.

**Comment by maxim-zhao** [comment]
> 
> 
> > how do these map?
> 
> actually there are 6, o, a, do, da, um, uma, I set up a table to explain it better, um/uma is used in items. Example: "usou uma PelorieMate", "Equipou um Escudo de Couro". do/da is used in battle. Example: "desviou do ataque da Medusa", "desviou do ataque do Escorpião". The Upper in the script will only use "O" and "A", Example: "O Escorpião desviou do ataque" "A Lente Dourada desviou do ataque" The plurals only the "as" will be used in "as Frutas de Laerma". the rest it seems that there will be no need...

So I guess um, uma, uns, umas is like "a" in English (indefinite article); o, a, os, as is like "the" (definite article); and do, da, dos, das is like "of" (possessive). Articles can be at the start of a sentence so the they may need capital letters. So I think we have this table:

|                  | Code   | Masculine single indefinite | Masculine plural indefinite | Feminine single indefinite | Feminine plural indefinite | Masculine single definite | Masculine plural definite | Feminine single definite | Feminine plural definite |
|------------------|--------|-----------------------------|-----------------------------|----------------------------|----------------------------|---------------------------|---------------------------|--------------------------|--------------------------|
| Lower indefinite | `<um>` | um                          | uns                         | uma                        | umas                       | o                         | a                         | os                       | as                       |
| Upper indefinite | `<Um>` | Um                          | Uns                         | Uma                        | Umas                       | O                         | A                         | Os                       | As                       |
| Possessive       | `<do>` | do                          | da                          | dos                        | das                        | do                        | da                        | dos                      | das                      |

The "code" column is what you would use in the script, and the second row of the table is what you'd use in the item lists to select the column (with [um], [uns] etc).

I've also done some work on the Polaris font:

![image](https://user-images.githubusercontent.com/7792986/104782994-0ddc4500-577d-11eb-97f9-a3f37f8c605d.png)

This is using 69/70 available tiles. I think accented capitals will just look bad, though, so it'd be nice to drop them and some of the ugliness here can be reduced.

**Comment by maxim-zhao** [comment]
I've inserted this font; for some reason I thought I had one spare character but I seem to be wrong, this is maxed out. Example:
![image](https://user-images.githubusercontent.com/7792986/104790002-2ef96180-578e-11eb-8354-13de1505cf2c.png)
The article handlers are not done yet and I suspect there will be some bad glitches with accented characters because it is overlapping with the scripting codes area now. I should be able to rearrange things quite easily.

**Comment by ajkmetiuk** [comment]
> So I think we have this table:

Yes, that's right, I just didn't know how to explain it to you, but that's correct.

> I've also done some work on the Polaris font:

Wow, it was very nice, maybe we can edit the 5 a little bit to be halfway between 5 / S, but the other characters are good...

**Comment by ajkmetiuk** [comment]
> I've inserted this font; for some reason I thought I had one spare character but I seem to be wrong, this is maxed out. Example:
> ![image](https://user-images.githubusercontent.com/7792986/104790002-2ef96180-578e-11eb-8354-13de1505cf2c.png)
> The article handlers are not done yet and I suspect there will be some bad glitches with accented characters because it is overlapping with the scripting codes area now. This might be tricky to solve...

for me it was good, I will try to remove Á, É, Ó and à from the script, so it is only 11 characters, maybe "help" a little.

**Comment by ajkmetiuk** [comment]
I edited the 5 / S a little bit, it seems to have improved, I made two models. The first looks better to me.
![model 1](https://user-images.githubusercontent.com/46766099/104796799-345ba980-5798-11eb-9170-918b0b11cfe6.jpg)
![model 2](https://user-images.githubusercontent.com/46766099/104796802-36be0380-5798-11eb-9d35-1be6f8b8bffd.jpg)

**Comment by damieng** [comment]
![6g-and-lj](https://user-images.githubusercontent.com/118951/104808546-f2a22180-57de-11eb-9216-560af0ae3bd2.png)

Here's a tweak that lets you use L and J as horizontal flips that gains you another character space.

Also here is a 6 that can be used as either a 6 or a G.

**Comment by maxim-zhao** [comment]
6 is already doubly flipped to make g, which I guess will look a bit odd with the loop open. As the majority of text is lowercase, I think it's good to optimise for that.

**Comment by maxim-zhao** [comment]
We may be able to pull back an extra character by removing á...

**Comment by ajkmetiuk** [comment]
> We may be able to pull back an extra character by removing á...

à... 

I see a little bug in this window, has the <end> tag so it's hard to see. 
![Capturar](https://user-images.githubusercontent.com/46766099/104828329-fc5f6f80-5846-11eb-8c9b-c8bd01c54c52.JPG)

**Comment by maxim-zhao** [comment]
This is a funny one, the wrapping logic is confused by the number so I worked around it with a manual line break.

**Comment by maxim-zhao** [comment]
- [ ] Bug with "Carta[ do Governador-Geral]" - [] skipping code does not work at the end of an item.

**Comment by ajkmetiuk** [comment]
> * [ ]  Bug with "Carta[ do Governador-Geral]" - [] skipping code does not work at the end of an item.

as there is only one letter in the game, I think can easily leave only "Carta" and fix this bug.

**Comment by maxim-zhao** [comment]
I think I fixed it in 21976f8cecf039c87aa3ed47ebecfee5d2899bd5. Testing is welcome...

**Comment by ajkmetiuk** [comment]
> I think I fixed it in [21976f8](https://github.com/maxim-zhao/psrp/commit/21976f8cecf039c87aa3ed47ebecfee5d2899bd5). Testing is welcome...

tested here, all right now!
![1](https://user-images.githubusercontent.com/46766099/105124028-fde39e80-5ab7-11eb-9d44-83fbc124cd43.jpg)
![2](https://user-images.githubusercontent.com/46766099/105124033-fe7c3500-5ab7-11eb-900f-e2d1df6056e1.jpg)
