### ISSUE TITLE
(Presentation) Meseta/Yes-No window overlap in hospital

### ISSUE THREAD

**Issue by gensakudan** [maxim-zhao/psrp#72]
When healing someone in the hospital (this issue might be present in other locations, too, but I haven't checked), if the meseta and the yes/no windows are greater than a certain combined width, the latter will partially cover up the former. See image below as an example from the German translation-in-progress.

![image](https://user-images.githubusercontent.com/90138378/168583406-ad9aa68f-4a2b-4ccb-bcef-3609de6c3bab.png)

**Comment by maxim-zhao** [comment]
It applies in the shop when buying/selling too.

**Comment by maxim-zhao** [comment]
![image](https://user-images.githubusercontent.com/7792986/169574775-aa538aad-7289-41d1-9699-ef0263a95cb3.png)
![image](https://user-images.githubusercontent.com/7792986/169574985-9acdb5b3-a23a-4ac4-a21c-b2c2ae59e82d.png)
Much better...
