### ISSUE TITLE
Implement declension for item and enemy names

### ISSUE THREAD

**Issue by gensakudan** [maxim-zhao/psrp#73]
The following is some functionality that will be necessary for the German translation of this retranslation project. The way I imagine it, it will be an expansion of the article system used in all other languages, while preferably retaining full backwards compatibility. The crux of this enhancement is that the list of articles will be expanded into a two-dimensional lookup table, so that both gender and case can be used to find the correct article to use and make adjustments to the item/enemy name string itself to make it grammatically correct.

In order to achieve said backwards compatibility, the lookup table for other options could simply have only a single unique case to work with.

-----

To start with, these tokens are to be added (both upper- and lowercase for the case indicators):
- `<Nom>`: nominative case indicator
- `<Gen>`: genitive case indicator
- `<Dat>`: dative case indicator
- `<Acc>`: accusative case indicator
- `<Der>`: definite masculine singular
- `<Die>`: definite feminine singular
- `<Das>`: definite neuter singular
- `<DieP>`: definite plural (lowercase is `<dieP>`)※
- `<Ein>`: indefinite masculine singular
- `<Eine>`: indefinite feminine singular
- `<EinN>`: indefinite neuter singular (lowercase is `<einN>`)

※This token may not be necessary to implement at all, as only one item name is in plural, item names in the message box will always be in accusative case, and definite plural accusative uses the same article as definite feminine singular accusative (see table below).

**Note:** Lowercase `<nom>` and uppercase `<Gen>`, `<Dat>` and `<Acc>` may not be necessary to implement and thus can be omitted if memory constraints become an issue. They are still listed below for the sake of completeness, however.

Next, it will be necessary to create a lookup table that can get the correct article to use from both the case indicator and the gender:

| | `<Der>` | `<Die>` | `<Das>` | `<DieP>` | `<Ein>` | `<Eine>` | `<EinN>`
| --- | --- | --- | --- | --- | --- | --- | --- |
| `<Nom>` | Der | Die | Das | Die | Ein | Eine | Ein |
| `<nom>` | der | die | das | die | ein | eine | ein |
| `<Gen>` | Des | Der | Des | Der | Eines | Einer | Eines |
| `<gen>` | des | der | des | der | eines | einer | eines |
| `<Dat>` | Dem | Der | Dem | Den | Einem | Einer | Einem |
| `<dat>` | dem | der | dem | den | einem | einer | einem |
| `<Acc>` | Den | Die | Das | Die | Einen | Eine | Ein |
| `<acc>` | den | die | das | die | einen | eine | ein |

Enemy names will be formatted as follows:
- an article token, assuming the enemy in question doesn't use a proper name (e.g. Lashiec, Tajim)
- the enemy name itself, with the following formatting in place:
  - text in square brackets (`[]`), which only gets printed if the name is rendered for the enemy name window in the top right hand corner of the screen (or, if it's an item name, in the item list)
  - text in curly brackets (`{}`), which only gets printed if the `<monster>` token was preceded by a `<Gen>` or `<gen>` token
  - text in round brackets (`()`), which only gets printed if the `<monster>` token was preceded by a `<Dat>`, `<dat>`, `<Acc>` or `<acc>` tag, or if the `<item>` token was preceded by an `<article>` token

**Example 1:** Consider the following enemy name string: `<Der> Lebende[r]{n}(n) Tote[r]{n}(n)`.
- In the enemy name window, the article will be omitted and the characters in curly and round brackets will not be printed, outputting `Lebender Toter`.
- If the `<Nom>` token is applied, nothing in *any* of the brackets will be printed, outputting `Der Lebende Tote`.
- If the `<Gen>` token is applied, the characters in square and round brackets will not be printed, outputting `Des Lebenden Toten`.
- If the `<Dat>` or `<Acc>` token is applied, the characters in square and curly brackets will not be printed, outputting either `Dem Lebenden Toten` (in dative) or `Den Lebenden Toten` (in accusative).

**Example 2:** Consider the only item name to use any sort of bracket tags: `<Ein> Weiße[r](n) Mantel`.
- In the item list, the article will be omitted and the character in round brackets will not be printed, outputting `Weißer Mantel`.
- Item names printed in the message box are **always in accusative case**, and the character in square brackets will not be printed, outputting `Einen Weißen Mantel`.

**Note:** The use of square backets in this example may conflict with the current practice of using square brackets in item names to indicate what part of the name only gets printed if the item name is written to the message box. A different (set of) character(s) may be used for tagging those if necessary.

-----

In summary, here is a flowchart of what the algorithm to be written for this is expected to do for enemy names:
1. ***(Skip to step 3 if the enemy name is being written to the name window.)*** Read the case token (`<Nom>`, `<Gen>`, etc.) and store it somewhere in memory.
2. Check the enemy name to see if it has a gender token (`<Der>`, `<Die>` or `<Das>`). If it does, use this token and the case token from the previous step to look up the article to write to the text box. If it doesn't, carry on.
3. Iterate through the rest of the enemy name string, character by character.
    - If the character is not an open or closed bracket of any sort, print it as-is.
    - If the character is an open square bracket (`[`) and you're writing the string to the enemy name window, print all the characters until you reach a closed square bracket (`]`). Otherwise skip.
    - If the character is an open curly bracket (`{`) and the case token from step 1 was either `<Gen>` or `<gen>`, print all the characters until you reach a closed curly bracket (`}`). Otherwise skip.
    - If the character is an open round bracket (`(`) and the case token from step 1 was either `<Dat>`, `<dat>`, `<Acc>` or `<acc>`, print all the characters until you reach a closed round bracket (`)`). Otherwise skip.
    - Keep in mind that a given enemy string can have more than one pair of each type of bracket.

And here is what it is expected to do for item names:
1. If you see the `<article><item>` tokens in a text box string, set the case to `<acc>` (lowercase accusative).
2. Check the item name for article tokens, same as step 2 in the above flowchart.
3. Iterate through the rest of the item name string, again, same as step 3 in the above flowchart. The only difference is that checking for curly brackets won't be necessary.

**Comment by maxim-zhao** [comment]
The German script so far seems to only have `<Nom>`, `<gen>`, `<dat>`, no other case combinations. The item tables seem to only have `<Eine>`, `<Ein>`, `<Die>` and `<Das>`. Is this because it's still incomplete?

**Comment by gensakudan** [comment]
I'd brought it up in the first draft of the original post, but I seem to have edited it out at some point. Hmm...

Anyway, you're mostly right. For enemy names, only `<Nom>`, `<gen>` and `<dat>` are used in the German script, although if implemented, I could also see at least one line where I'd like to use `<acc><monster>`.

As for items:
> And here is what it is expected to do for item names:
> 
> 1.    If you see the `<article><item>` tokens in a text box string, set the case to <acc> (lowercase accusative).

The idea for now being that the `<article>` token would be functionally identical to the `<acc>` token (although I could go into the script and replace the `<article>` tokens if that's necessary).

**Comment by maxim-zhao** [comment]
I've pushed some changes to my "brackets" branch that I think do a simplified version of this. Let's see what the gaps are...

1. Only these tags are supported in the script: `<Nom>`, `<gen>`, `<dat>` (more can be added easily enough)
2. There's a mechanism to select which bracketed portions are shown for any given `<item>`/`<player>`/`<enemy>` tag substitution
3. For the enemy name window, we select the `[]` parts
4. If we see a `<Nom>` tag, we discard all bracketed parts (and emit one of Der, Die, Das, Ein, Eine, Ein)
5. If we see a `<gen>` tag, we select only the `{}` parts (and emit one of des, der, des, eines, einer, eines)
6. If we see a `<dat>` tag, we select only the `()` parts (and emit one of dem, der, dem, einem, einer, einem)

So no `<acc>` yet and I think we are missing a way to get the possessive suffix (Alisas, Lutz', etc) where needed. What do I need to do for these two? Are they the same thing? Do we need to add a `<Name>` token (similar to other languages)?

**Comment by maxim-zhao** [comment]
(Side note: Why is Dark Force given a definite article? Isn't that a name?)

**Comment by gensakudan** [comment]
> The current code will emit no `[]`, `{}` or `()` parts for items in the inventory, shop or anywhere but the script. Is there a case for some characters needed there? It just needs another bracket...

The White Mantle, which is currently listed as `<Ein> Weiße[r](n) Umhang`. The part in `[]` would be rendered for the inventory and shop to produce `Weißer Umhang` as the output, but as it conflicts with the current use of `[]` in item names, you're welcome to give it different tags of your choice. (Also, just to dispel any uncertainty, the `()` part would be used for the accusative case to output `einen Weißen Umhang` to the message box.)

> So I guess next I need some `<acc>` in the script please :)

The tokens in the script.yaml are converted outside of the assembler, right? For the time being, you could have `<article>` be treated the same way as `<acc>` until I get around to it in my second go over the script.

> (Side note: Why is Dark Force given a definite article? Isn't that a name?)

Personal preference. Translated into German, it just doesn't feel like a proper name, so it's using an article instead. None of the translations so far are final, though, so it might still be subject to change.

**Comment by maxim-zhao** [comment]
I guess this is done now...
