### ISSUE TITLE
(German Translation) Bug with declension tags

### ISSUE THREAD

**Issue by gensakudan** [maxim-zhao/psrp#78]
#### What happens:
In battle, if two consecutive actions display messages so that the first message has `<gen>` as its last used declension tag and the second message starts with `<player>` (or at least contains no declension tags before that token), the player name is erroneously rendered in its possessive form.

#### To reproduce:
There are likely several instances in which this can happen, but this is the one I found it the most consistent with:
1. Enter into a battle with two or more enemies.
2. Let it play out a turn in such a way that two enemies attack back-to-back and both miss their attacks. If anything happens between two enemy attacks missing, even if it doesn't display a message, it won't trigger the bug.

#### Expected behavior:
If the `<player>` token is on its own, the player name should be rendered without its possessive suffix at all times. The possessive suffix should *only* be rendered if `<player>` is immediately preceded by `<gen>`.

**Comment by maxim-zhao** [comment]
You'll need to merge my master branch to get this fix. It contains all changes from languages/de.
