### ISSUE TITLE
(Feature Request) Variable width for shop inventory windows

### ISSUE THREAD

**Issue by gensakudan** [maxim-zhao/psrp#79]
For translations that have longer item names (e.g. German), it tends to look a little unsightly when the items a shop has in stock all have relatively short names, as it leads to a lot of empty space between the item names and the prices, which also hampers readability a bit.

If possible, I think the width of the shop inventory window should be relative to the length of the longest item name it contains.

**Comment by maxim-zhao** [comment]
Some progress...
![ps1jert-91](https://user-images.githubusercontent.com/7792986/189413719-0f2c7225-4efb-4b3c-91f3-783446a2151b.png) ![ps1jert-92](https://user-images.githubusercontent.com/7792986/189413724-e0dc6a19-26df-4816-b1ae-4e1243b43121.png) ![ps1jert-93](https://user-images.githubusercontent.com/7792986/189413727-928fa99d-d5d0-4e3c-951b-0dc44990bb7f.png) ![ps1jert-96](https://user-images.githubusercontent.com/7792986/189413962-192e9af2-4b8b-4b89-8eae-79e011aef941.png) ![ps1jert-95](https://user-images.githubusercontent.com/7792986/189413958-178cfbaa-1430-4687-8e65-fbd79b309c2e.png) ![ps1jert-94](https://user-images.githubusercontent.com/7792986/189413956-9f85f04c-6ae8-4c7d-b74f-724a81c24315.png)

**Comment by maxim-zhao** [comment]
I leave space for prices up to 5 digits, with one space after the text, for the few items that need it (IceDecker, Diamond Armor). I don't feel like cramming it even closer by checking for the length of the price digits...
