### ISSUE TITLE
Include [optional] Easy Patches

### ISSUE THREAD

**Issue by Kroc** [maxim-zhao/psrp#8]
It would be nice to have compile-time options to include the easy-patches to reduce the amount of grinding: https://www.romhacking.net/hacks/4504/

Right now, I have the choice between a less grindy game, or a better translation :(

**Comment by maxim-zhao** [comment]
The patches do apply cleanly to the retranslation - but it might be good to have a custom “easy mode” collection of tweaks including reducing the random battle probability as well as the money and experience boosts.

**Comment by frankcifaldi** [comment]
I'd be interested in knowing if the specific enhancements M2 made could be applied to a ROM file, especially faster walking speed and reduced encounter rate. It's pretty hard for me to go back to the untouched game now!

**Comment by maxim-zhao** [comment]
Given the nature of the game, it’s likely we’ll need to just approximate the changes as the exact details are likely to be very hard to extract. I’m thinking a simple x2 on walking speed and enemy drops, /2 on enemy battles.

**Comment by maxim-zhao** [comment]
Walking speedup was surprisingly painful... needed to patch out various things dependent on a 1px per frame movement over 16 frames.

The other cheats are seemingly simpler as the romhacking patch applies simply enough. How many options do we need on the "easy mode"? I'm thinking just one...

**Comment by maxim-zhao** [comment]
Well, why not all of them?

![image](https://user-images.githubusercontent.com/7792986/69504830-0412d500-0f1e-11ea-88b1-747b8834f0fd.png)

Only thing left is the encounter rate...
