### ISSUE TITLE
(Feature Request) Pronoun token(s)

### ISSUE THREAD

**Issue by gensakudan** [maxim-zhao/psrp#80]
For messages that describe player actions, translations generally have to avoid using pronouns because Alisa might or might not be alive, which changes which character the pronoun would refer to. What I suggest is a set of `<He>`/`<His>`/`<Him>` (and corresponding lowercase) pronouns that output either male or female pronouns, depending on which name the `<player>` token would output in any given situation (i.e. `she/her/her` for Alisa, and `he/his/him` for everyone else).

Come to think of it, though, only the she/he pronouns might be necessary to implement, at least for English. Other languages would have to be handled on a case-by-case basis.

**Comment by maxim-zhao** [comment]
Except for the ambiguity of Lutz' gender (and in 2022, maybe some customised pronouns...)

**Comment by gensakudan** [comment]
Yeah, but this is a 1987 game, not a 2022 one.

**Comment by maxim-zhao** [comment]
Well, there was famously a script edit to change the Governor-General's script about taking the letter to Lutz, from "her" in the US version to "him" in the GBA version. Is the Japanese text gendered?
> ワタシノ　テガミヲ　モッテ<line>
> アイニ　ユクガヨイ。

> 私の手紙を持って会いに行くがよい。

Anyway - I'll think about how it might be possible to add this. I think there's quite a few script entries that make assumptions about who is alive, but at the same time the game code is often careful to handle cases where that's not the case (like Myau being unable to open certain bottles) and we will need to amend scripts in multiple languages to not assume Alis is the party leader.

**Comment by gensakudan** [comment]
> Well, there was famously a script edit to change the Governor-General's script about taking the letter to Lutz, from "her" in the US version to "him" in the GBA version. Is the Japanese text gendered?

There's no explicit gender given in the Japanese script because Japanese generally tries to avoid third-person pronouns, but the Lutz seen in Phantasy Star II is explicitly noted to be the same one as in this game, and the first time you see him, he just woke up from cryogenic sleep while wearing nothing but pants.

> we will need to amend scripts in multiple languages to not assume Alisa is the party leader

Shouldn't be much trouble once the code itself is implemented.

**Comment by maxim-zhao** [comment]
I'd kind of like to keep Lutz' gender ambiguous as I think that was an intention for Phantasy Star 1, based on comments from Rieko Kodama:

> Kodama: Actually, when I created the first draft of the characters for Phantasy Star II, I made Lutz the main character. By the way, since so many people have asked whether Lutz is male or female, let me say a little about that. In the original story drafts of Phantasy Star, Lutz was a hermaphrodite, and as Alisa grew up, Lutz could become male or female. I thought that was interesting so I depicted Lutz that way. 

https://shmuplations.com/phantasystar/

It's not clear to me whether the released version is still holding onto this though. Does the Japanese manual give any clues? https://www.smspower.org/Scans/PhantasyStar-SMS-JP-Manual?gallerypage=11

**Comment by maxim-zhao** [comment]
I'd kind of like to keep Lutz' gender ambiguous as I think that was an intention for Phantasy Star 1, based on comments from Rieko Kodama:

> Kodama: Actually, when I created the first draft of the characters for Phantasy Star II, I made Lutz the main character. By the way, since so many people have asked whether Lutz is male or female, let me say a little about that. In the original story drafts of Phantasy Star, Lutz was a hermaphrodite, and as Alisa grew up, Lutz could become male or female. I thought that was interesting so I depicted Lutz that way. 

https://shmuplations.com/phantasystar/

It's not clear to me whether the released version is still holding onto this though. Does the Japanese manual give any clues? https://www.smspower.org/Scans/PhantasyStar-SMS-JP-Manual?gallerypage=11

**Comment by gensakudan** [comment]
Well, there's the gender-neutral singular "they" in English if you *really* insist, but it'd require further script adjustments because most verbs are conjugated differently between he/she and they. There's also the fact that not all languages even *have* neutral third-person pronouns (German doesn't, at least), so I think the solution with the least headache would be to just go with Lutz being male, since a) that's his canon gender in the series lore and there's nothing in the final draft of the game to suggest any hermaphroditism, and b) the name "Lutz" isn't exactly unisex.

**Comment by gensakudan** [comment]
Also, for what it's worth, [the retranslation is already using he/him pronouns for Lutz, anyway](https://github.com/maxim-zhao/psrp/blob/master/psrp/script.yaml#L3137).

**Comment by maxim-zhao** [comment]
Do we need pronouns for enemies and items as well as the main four player characters?

**Comment by gensakudan** [comment]
Most likely not, or at least I haven't felt any need for them when I went through the script. Hell, even just the player pronouns would be highly situational and only used in a few lines at most.

**Comment by maxim-zhao** [comment]
I'm suspicious it may be desirable in French and other Latinate languages where we already have gendered "articles" - but I'll continue on the assumption that it's not. It is dependent on the game populating the player index correctly in the context of the line, can you give me examples of entries where you might use it?

**Comment by maxim-zhao** [comment]
![image](https://user-images.githubusercontent.com/7792986/192052039-abc5fa0d-9f4b-4221-b7fe-ec0e0a33e0a3.png)

**Comment by maxim-zhao** [comment]
Could you enumerate the pronouns you need for German so I can put them in? For English, I'm supporting `<he>`/`<she>` and `<his>`/`<her>`. Technically I can support up to 256 pronouns but they all have to be specifically added to the Python code (for now).

**Comment by maxim-zhao** [comment]
Current implementation doesn't wrap properly when using pronouns:

![image](https://user-images.githubusercontent.com/7792986/192246913-c7a392bc-be10-4a6b-9646-3aec9e61977c.png)

**Comment by maxim-zhao** [comment]
Closing as it now seems to all work properly. No pronouns yet in fr, pt-br, ca, es but they are easy to add.
