### ISSUE TITLE
Fix soft-locks in the original game

### ISSUE THREAD

**Issue by maxim-zhao** [maxim-zhao/psrp#84]
* If you use a Transer or the Fly spell after obtaining the Luveno, and the last church you visited was in Paseo. You can't go back to Palma because the spaceports are closed, and you can't leave the area around Paseo because you haven't gotten any other vehicles yet.
* If you kill Lassic, but Myau is dead, Alisa is either dead or doesn't have enough MP to cast Fly, Lutz is either dead or doesn't have enough MP to revive anyone, and you didn't buy a Transer. You then have no way of getting off the Air Castle.

**Comment by gensakudan** [comment]
### Suggestions for softlock fixes
These try to minimize invasiveness while also making sure to prevent other ways for a dedicated player to re-lock themself.

#### Luveno softlock
1. Upon returning Hapsby to Luveno, check current Fly/Transer destination.
2. If it's Paseo, set it to Alis's house.

#### Air Castle softlock
1. After Lassic dies, revive at least Myau (but ideally all party members).
2. Temporarily disable all encounters in the dungeon. If that's not possible, then instead warp the player directly to the castle entrance.
3. If possible, remove the Serpent encounter from one of the houses if it hasn't been fought yet.

**Comment by maxim-zhao** [comment]
I think this is now fixed - can you help test the Luveno/Troop fix?
