### ISSUE TITLE
Luveno doesn't recognize Hapsby in inventory

### ISSUE THREAD

**Issue by allenu** [maxim-zhao/psrp#94]
Hey guys, I don't know if this is the right place to report this bug. I'm using the translation I found on SMS Power and am stuck at the part where Luveno is supposed to offer to build me the ship. I was able to pick up Hapsby in Bortevo but when I head back to Gothic to chat with Luveno, he still says "Finally. What took you so long? First, I need you to fetch my assistant." etc. But I obviously have Hapsby in my inventory already.

I can supply OpenEmu save state if needed.

**Comment by allenu** [comment]
Also, I used the fly spell (i.e. "Troop") to get back to Gothic once I obtained Hapsby. I can try walking back to see if that makes any difference.

**Comment by andresanches** [comment]
@allenu Hapsby is the pilot, not the assistant. The assistant is a human being. He can be found on the passageway between Gothic and the Spaceport (the one with the blue walls). Take the first turn you see, he'll be there.

**Comment by allenu** [comment]
Oh wow, thanks for correcting me! I'm going to try this and then close out this issue.
